-- Your SQL goes here
ALTER TABLE sys_stats ADD COLUMN load_one DOUBLE PRECISION;
ALTER TABLE sys_stats ADD COLUMN load_five DOUBLE PRECISION;
ALTER TABLE sys_stats ADD COLUMN load_fifteen DOUBLE PRECISION;
