//! "Dcollector" TimescaleDB agent library.

#![forbid(unsafe_code)]
#![deny(
    missing_docs,
    unstable_features,
    missing_debug_implementations,
    missing_copy_implementations,
    trivial_casts,
    trivial_numeric_casts,
    unused_import_braces,
    bad_style,
    const_err,
    dead_code,
    improper_ctypes,
    non_shorthand_field_patterns,
    no_mangle_generic_items,
    overflowing_literals,
    path_statements,
    patterns_in_fns_without_body,
    private_in_public,
    unconditional_recursion,
    unused,
    unused_allocation,
    unused_comparisons,
    unused_parens,
    while_true,
    missing_debug_implementations,
    trivial_casts,
    trivial_numeric_casts,
    unused_extern_crates,
    unused_import_braces
)]


#[macro_use]
extern crate diesel;


#[global_allocator]
static GLOBAL: mimalloc::MiMalloc = mimalloc::MiMalloc;


/// RDBM models
pub mod models;
/// Postgres functions
pub mod postgres;
/// Autogenerated Diesel schema
#[allow(missing_docs)]
pub mod schema;
/// System info API
pub mod systeminfo;
/// UPS API
pub mod ups;


pub use models::{DiskStat, ProcStat, SysStat, UpsStat};
pub use schema::{disk_stats, proc_stats, sys_stats, ups_stats};
pub use std::{
    fmt::Display,
    time::{SystemTime, UNIX_EPOCH},
};
pub use tracing::{debug, error, info, instrument, trace, warn};
